# Generated by Django 5.2.7 on 2025-10-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("demo_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book_shelf",
            name="location",
        ),
    ]
